name: universal_html_flutter_test
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  universal_html:
    path: '..'

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.1
  stream_channel: ^2.1.0
  test: ^1.24.0